### ISSUE TITLE
[lw2-survey-saver] Замечания

### ISSUE THREAD

**Issue by andrey-ilyin** [halmer/labs#1]
- Сократить количество передаваемых переменных в функции
  GetSurveyToFile($surveyInfo['email'], $surveyInfo);
  до
  GetSurveyToFile($surveyInfo);

Название функции должно быть SaveSurveyToFile
- Код по формированию пути к файлу анкеты нужно вынести в отдельную функцию
  GetSurveyFilePath($email)
- Функцию GetSurveyFromFile нужно переписать.
  Функция должна возвращать, либо массив с данными, если все проверки прошли успешно и данные удалось прочитать, либо false в том случае, если что-то пошло не так.
  Код ошибки будет записан в переменную $errorCode, которая передается по ссылке. 
  http://php.net/manual/ru/language.references.pass.php

``` php
    /**                                         
     * @param string $email
     * @param string $errorCode
     * @return array|false
     */
    function GetSurveyFromFile($email, &$errorCode)
```

См. https://ru.wikipedia.org/wiki/PHPDoc
- Для задания кодов ошибок нужно использовать константы

``` php
    define('ERR_NO_FILE', 'no_file');
    define('ERR_NO_ACCESS_TO_FILE', 'no_access');
```
- Вывод информации об анкете нужно оформить в виде функции PrintSurvey($survey)

**Comment by halmer** [comment]
Исправил замечания
